# This config file runs the CNN-based RL chess agent model
model: "CNN_Agent" # Name of the model being trained, determines the output directory name
model_class: "CNN" # Should match one of the model classes in core/torch_models.py

output:
    output_path: &output_path "results/CNN_Agent/" # Directory of training results
    pretrain_path: !join_path [*output_path, "pretrain/"] # Location of pretrain model results

    model_output: !join_path [*output_path, "saved_weights/"] # Location of saved model weights
    log_path: !join_path [*output_path, "log.txt"] # Location of training log
    plot_output: *output_path # Location of eval scores during training summary plot and csv data
    record_path: !join_path [*output_path, "recordings/"] # Location of where to save episode recordings
    tensorboard: !join_path [*output_path, "tensorboard/"] # Location to save tensorboard log files
    clear_all: False # If set to True, then the output_path is cleared at the start, deletes existing results

pretrain: # Specifies the supervised pre-training parameters
    batch_size: 1024
    lr_start: 1.0e-3
    lr_end: 1.0e-6
    weight_decay: 1.0e-2
    train_num_steps: 75000
    grad_clip: 1.0
    eval_every: 5000
    save_every: 25000
    use_amp: True
    use_latest_checkpoint: True
